// Code generated by ogen, DO NOT EDIT.

package openapi

// OperationName is the ogen operation name
type OperationName = string

const (
	CreateNewQuoteGameOperation OperationName = "CreateNewQuoteGame"
	GetRandomQuoteOperation     OperationName = "GetRandomQuote"
)
