// Code generated by ogen, DO NOT EDIT.

package api

type InternalServerErrror struct {
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *InternalServerErrror) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *InternalServerErrror) SetMessage(val string) {
	s.Message = val
}

func (*InternalServerErrror) getRandomQuoteRes() {}

// A basic quote.
// Ref: #/components/schemas/Quote
type Quote struct {
	ID     float64 `json:"id"`
	Quote  string  `json:"quote"`
	Author string  `json:"author"`
}

// GetID returns the value of ID.
func (s *Quote) GetID() float64 {
	return s.ID
}

// GetQuote returns the value of Quote.
func (s *Quote) GetQuote() string {
	return s.Quote
}

// GetAuthor returns the value of Author.
func (s *Quote) GetAuthor() string {
	return s.Author
}

// SetID sets the value of ID.
func (s *Quote) SetID(val float64) {
	s.ID = val
}

// SetQuote sets the value of Quote.
func (s *Quote) SetQuote(val string) {
	s.Quote = val
}

// SetAuthor sets the value of Author.
func (s *Quote) SetAuthor(val string) {
	s.Author = val
}

func (*Quote) getRandomQuoteRes() {}
